<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="AES_BranchLocator_Intf_branchesInfoHttp_Service" targetNamespace="http://AES_BranchLocator_Svcs_v1/com/apria/services/aes/branchlocator/branchesInfo/Binding" xmlns:Port_0="http://AES_BranchLocator_Svcs_v1/com/apria/services/aes/branchlocator/branchesInfo" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:this="http://AES_BranchLocator_Svcs_v1/com/apria/services/aes/branchlocator/branchesInfo/Binding" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <wsdl:import location="branchesInfo.wsdl" namespace="http://AES_BranchLocator_Svcs_v1/com/apria/services/aes/branchlocator/branchesInfo">
    </wsdl:import>
  <wsdl:binding name="AES_BranchLocator_Intf_branchesInfoHttpBinding" type="Port_0:branchesInfo">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="getBranchesInfo">
      <soap:operation soapAction=""/>
      <wsdl:input name="getBranchesInfoRequest">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="getBranchesInfoResponse">
        <soap:body use="literal"/>
      </wsdl:output>
      <wsdl:fault name="fault">
        <soap:fault name="fault" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="AES_BranchLocator_Intf">
    <wsdl:port binding="this:AES_BranchLocator_Intf_branchesInfoHttpBinding" name="AES_BranchLocator_Intf_branchesInfoHttpPort">
      <soap:address location="http://aesb.apria.com:80/AES_BranchLocator_Svcs_v1Web/sca/AES_BranchLocator_Intf"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>