Select RFRL_ID, ZIP_CD, ST_CD, CITY_NM, RFRL_NM, ACCT_VAL_CD, RFRL_SUB_TYPE_NM, VALID_RFRL_SRC_IN
from ODS.M_MPI_PROFILE_SEARCH
WHERE VALID_RFRL_SRC_IN='Y' 
[CONDITION]

ORDER BY RFRL_NM, CITY_NM
FETCH FIRST 101 ROWS ONLY OPTIMIZE FOR 101 ROWS
WITH UR
