//
// Generated By:JAX-WS RI IBM 2.1.1 in JDK 6 (JAXB RI IBM JAXB 2.1.3 in JDK 1.6)
//


package com.apria.web.services.mobile.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

@XmlRootElement(name = "getIntakeWOListResponse", namespace = "http://mobile.services.web.apria.com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getIntakeWOListResponse", namespace = "http://mobile.services.web.apria.com/")
public class GetIntakeWOListResponse {

    @XmlElement(name = "return", namespace = "")
    private com.apria.web.services.mobile.out.IntakeResult _return;

    /**
     * 
     * @return
     *     returns IntakeResult
     */
    public com.apria.web.services.mobile.out.IntakeResult getReturn() {
        return this._return;
    }

    /**
     * 
     * @param _return
     *     the value for the _return property
     */
    public void setReturn(com.apria.web.services.mobile.out.IntakeResult _return) {
        this._return = _return;
    }

}
