//
// Generated By:JAX-WS RI IBM 2.1.1 in JDK 6 (JAXB RI IBM JAXB 2.1.3 in JDK 1.6)
//


package com.apria.web.services.mobile.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

@XmlRootElement(name = "getIntakeWOList", namespace = "http://mobile.services.web.apria.com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getIntakeWOList", namespace = "http://mobile.services.web.apria.com/")
public class GetIntakeWOList {

    @XmlElement(name = "arg0", namespace = "")
    private com.apria.web.services.mobile.in.SearchRequest arg0;

    /**
     * 
     * @return
     *     returns SearchRequest
     */
    public com.apria.web.services.mobile.in.SearchRequest getArg0() {
        return this.arg0;
    }

    /**
     * 
     * @param arg0
     *     the value for the arg0 property
     */
    public void setArg0(com.apria.web.services.mobile.in.SearchRequest arg0) {
        this.arg0 = arg0;
    }

}
