SELECT
 *
FROM  
(
SELECT
	SUBSTRING(O.ORDER_NUMBER,1,8) ORDER_NUMBER,
	SUBSTRING(O.ORDER_NUMBER,9,11) LINE_ITEM,
	SUBSTRING(R.ROUTE_ID, 1,4) BU,
	R.DATE_MODIFIED,
    R.ROUTE_ID,
    S.INTERNAL_STOP_ID,
    S.STOP_IX,
	SUBSTRING(S.LOCATION_ID, CHARINDEX(S.LOCATION_ID,'-')+1,LEN(S.LOCATION_ID)-CHARINDEX(S.LOCATION_ID,'-' )) AS PATIENT_ID,
	S.ACTUAL_ARRIVAL,
	S.PROJECTED_ARRIVAL,
	S.ACTUAL_DEPARTURE,
	S.PROJECTED_DEPARTURE,
	S.PLANNED_ARRIVAL,
	S.CANCELLED,
	S.UNDELIVERABLE,
	R.ROUTE_DATE,
	R.REGION_ID,
	R.DRIVER1_NAME DRIVER_NAME,
	L.TYPE, 
	L.ID,
	L.DESCRIPTION PATIENT_NAME,
	L.ADDR_LINE1,
	L.ADDR_LINE2,
	L.REGION1 CITY,
	L.REGION3 STATE_CD,
	L.POSTAL_CODE,
	L.PHONE_NUMBER,
	L.LATITUDE,
	L.LONGITUDE,
	O.SPECIAL_INSTRUCTIONS,
    LTRIM(RTRIM(SUBSTRING(O.SPECIAL_INSTRUCTIONS ,5, 7)))  AS PRODUCT_CODE,
    SUBSTRING(O.SPECIAL_INSTRUCTIONS ,12,51) AS PRODUCT_DESC,
    SUBSTRING(O.SPECIAL_INSTRUCTIONS ,52,(LEN(O.SPECIAL_INSTRUCTIONS)-1)) AS COMMENTS,
	CASE WHEN S.CANCELLED ='F' AND S.ACTUAL_ARRIVAL IS NULL  AND S.PROJECTED_ARRIVAL >= DATEADD(HH,+8,GETDATE())
         THEN S.PROJECTED_ARRIVAL END ETA,
	CASE WHEN S.CANCELLED ='F' AND S.ACTUAL_ARRIVAL IS NULL  AND S.PROJECTED_ARRIVAL >= DATEADD(HH,+8,GETDATE())
         THEN S.PROJECTED_ARRIVAL - 60/1440 END DELIVERY_WINDOW_START_DT,
	CASE WHEN S.CANCELLED ='F' AND S.ACTUAL_ARRIVAL IS NULL  AND S.PROJECTED_ARRIVAL >= DATEADD(HH,+8,GETDATE())
         THEN S.PROJECTED_ARRIVAL + 180/1440 END DELIVERY_WINDOW_END_DT,
	CASE WHEN S.CANCELLED ='F' THEN 
	CASE WHEN S.ACTUAL_ARRIVAL IS NULL	
             THEN
	       CASE WHEN S.PROJECTED_ARRIVAL >= DATEADD(HH,+8,GETDATE())
                     THEN
		       CASE WHEN S.PROJECTED_ARRIVAL > S.PLANNED_ARRIVAL + 30/1440	
                            THEN 'Behind Schedule'
					WHEN  S.PROJECTED_ARRIVAL < S.PLANNED_ARRIVAL-30/1440	THEN 'Ahead of Schedule'
					ELSE 'On Schedule' 
				END
				ELSE  'Incomplete'
			END
			ELSE
				CASE WHEN S.UNDELIVERABLE = 'T' THEN 'Undeliverable' 
					ELSE CASE WHEN  S.ACTUAL_DEPARTURE IS NULL THEN 'On Site'
							ELSE 'Delivered'
						END
				END
		END
		ELSE 'Cancelled/Rescheduled'
	END DELIVERY_STATUS,
	CASE 
    --WHEN O.PLANNED_SIZE1 =0 AND O.PLANNED_PICKUP_SIZE1<>0 AND SUBSTR(O.PLANNED_SIZE3,1,2)='40' THEN 'Pickup Only'
	--WHEN O.PLANNED_SIZE1 =0 AND O.PLANNED_PICKUP_SIZE1<>0 AND SUBSTR(O.PLANNED_SIZE3,1,2)='50' THEN 'Exchange Pickup'
		WHEN O.PLANNED_SIZE1 =0 AND O.PLANNED_PICKUP_SIZE1<>0  THEN 'Pickup'
		WHEN O.PLANNED_SIZE1 <>0 AND O.PLANNED_PICKUP_SIZE1=0 AND Substring(cast(O.PLANNED_SIZE3 as varchar),1,2)='50' THEN 'Exchange Delivery'
		WHEN O.PLANNED_SIZE1 <>0 AND O.PLANNED_PICKUP_SIZE1=0 AND Substring(cast(O.PLANNED_SIZE3 as varchar),1,2) in ('20','10') THEN 'Delivery' ELSE NULL
	END DELIVERY_TYPE,
 RANK() OVER ( PARTITION BY O.ORDER_NUMBER 
                            ORDER BY  CASE WHEN S.CANCELLED ='F' AND S.UNDELIVERABLE ='F' THEN 1 ELSE 2 END, R.DATE_MODIFIED DESC)  Rank,
							                                                ROW_NUMBER() OVER(ORDER BY S.STOP_IX) AS RowNum
FROM TSDBA.DP_ROUTE R 
	JOIN TSDBA.DP_STOP S ON R.ROUTE_ID = S.ROUTE_ID AND R.REGION_ID = S.REGION_ID AND R.ROUTE_DATE = S.ROUTE_DATE 
	JOIN TSDBA.DP_ORDER O ON S.ROUTE_ID = O.ROUTE_ID AND S.REGION_ID = O.REGION_ID AND S.ROUTE_DATE = O.ROUTE_DATE AND S.INTERNAL_STOP_ID = O.INTERNAL_STOP_ID 
	JOIN TSDBA.TS_LOCATION L ON L.REGION_ID = S.REGION_ID AND L.TYPE = S.LOCATION_TYPE AND L.ID = S.LOCATION_ID
	JOIN TSDBA.DP_ROUTE_DRIVER D ON R.ROUTE_ID = D.ROUTE_ID AND R.REGION_ID = D.REGION_ID AND R.ROUTE_DATE = D.ROUTE_DATE 
WHERE  
	SUBSTRING(O.ORDER_NUMBER,1,1) IN ('X','W')
    [CONDITION]
    --ORDER BY S.STOP_IX
) aa
WHERE 
Rank = 1 
AND LEN(REPLACE(LINE_ITEM, 'x0123456789', 'x')) IS NOT NULL
AND RowNum < 501
