WITH BU_CC AS
(
   SELECT
   A.SRC_ORG_EN_ID AS BU, C.SRC_ORG_EN_ID AS CC
   FROM EDW.T_ORG_XREF A JOIN EDW.O_ORG_HRCHY B ON A.ORG_EN_UNQ_SK = B.ORG_EN_UNQ_SK JOIN EDW.T_ORG_XREF C ON B.PARENT_ORG_EN_UNQ_SK = C.ORG_EN_UNQ_SK
   WHERE B.ORG_HRCHY_TYPE_CD = 'STD'
   AND B.CURR_IN = 'Y'
   AND A.SRC_CD = 'ACIS'
   AND A.SRC_LVL_CD = 'BU'
   AND C.SRC_CD = 'JDE'
   AND C.SRC_LVL_CD = 'CC'
)
SELECT * FROM (
SELECT
A.BU, B.GMT_OFF_SET_HR OFFSET_HR
FROM BU_CC A JOIN EDW.SRC_GMT_OFFSET B ON A.BU = B.SRC_BU_ID
WHERE NOT EXISTS
(
   SELECT
   *
   FROM EDW.SRC_DYLGT_SVNG
   WHERE CURRENT_DATE BETWEEN DYLGT_SVNG_STRT_DT
   AND DYLGT_SVNG_END_DT
)
UNION
SELECT
A.BU, B.GMT_OFF_SET_HR OFFSET_HR
FROM BU_CC A JOIN EDW.SRC_GMT_OFFSET B ON A.CC = B.SRC_COST_CNTR_ID
WHERE SRC_BU_ID = ''
AND NOT EXISTS
(
   SELECT
   *
   FROM EDW.SRC_DYLGT_SVNG
   WHERE CURRENT_DATE BETWEEN DYLGT_SVNG_STRT_DT
   AND DYLGT_SVNG_END_DT
)
UNION
SELECT
A.BU, B.DYLGT_SVNG_OFFSET_HR OFFSET_HR
FROM BU_CC A JOIN EDW.SRC_GMT_OFFSET B ON A.BU = B.SRC_BU_ID
WHERE EXISTS
(
   SELECT
   *
   FROM EDW.SRC_DYLGT_SVNG
   WHERE CURRENT_DATE BETWEEN DYLGT_SVNG_STRT_DT
   AND DYLGT_SVNG_END_DT
)
UNION
SELECT
A.BU, B.DYLGT_SVNG_OFFSET_HR OFFSET_HR
FROM BU_CC A JOIN EDW.SRC_GMT_OFFSET B ON A.CC = B.SRC_COST_CNTR_ID
WHERE SRC_BU_ID = ''
AND EXISTS
(
   SELECT
   *
   FROM EDW.SRC_DYLGT_SVNG
   WHERE CURRENT_DATE BETWEEN DYLGT_SVNG_STRT_DT
   AND DYLGT_SVNG_END_DT
) ) A WHERE A.BU = ?
