SELECT  DISTINCT
	SUBSTRING(O.ORDER_NUMBER,1,8) ORDER_NUMBER,
    S.LOCATION_ID,
	S.PROJECTED_ARRIVAL,
	CASE WHEN L.TIMEZONE = 15 THEN 'US/Pacific'
              WHEN L.TIMEZONE = 13 THEN 'US/Arizona'
              WHEN L.TIMEZONE = 14 THEN 'US/Mountain'
              WHEN L.TIMEZONE = 8 THEN 'US/Eastern'
              WHEN L.TIMEZONE = 10 THEN 'US/Central'
              WHEN L.TIMEZONE = 17 THEN 'US/Hawaii'
              END TIME_ZONE,
    S.TW1_OPEN_TIME,
    S.TW1_CLOSE_TIME 
FROM TSDBA.DP_ROUTE R WITH (NOLOCK) 
	JOIN TSDBA.DP_STOP S WITH (NOLOCK) ON R.ROUTE_ID = S.ROUTE_ID AND R.REGION_ID = S.REGION_ID AND 
	R.ROUTE_DATE = S.ROUTE_DATE JOIN TSDBA.DP_ORDER O WITH (NOLOCK) ON S.ROUTE_ID = O.ROUTE_ID AND
	S.REGION_ID = O.REGION_ID AND S.ROUTE_DATE = O.ROUTE_DATE 
	AND S.INTERNAL_STOP_ID = O.INTERNAL_STOP_ID 
	JOIN TSDBA.TS_LOCATION L WITH (NOLOCK) ON L.REGION_ID = S.REGION_ID AND 
	L.TYPE = S.LOCATION_TYPE AND L.ID = S.LOCATION_ID
WHERE  
    R.ROUTE_DATE =  CONVERT(DATETIME, CONVERT(DATE, GETDATE()))
	AND    S.CANCELLED='F' 
	AND    S.UNDELIVERABLE ='F'
    AND    S.INTERNAL_STOP_ID < 5000
	AND    S.ACTUAL_ARRIVAL IS NULL
    AND    S.LOCATION_TYPE NOT IN ('AFH','DPT','SIT')
	AND    (
                R.ROUTE_ID NOT LIKE '%BASE%' AND
                R.ROUTE_ID NOT LIKE '%CLINIC%' AND
                R.ROUTE_ID NOT LIKE '%OC%'AND
                R.ROUTE_ID NOT LIKE '%HAL%'AND
                R.ROUTE_ID NOT LIKE '%AL%' AND
                R.ROUTE_ID NOT LIKE '%COU%' AND
                R.ROUTE_ID NOT LIKE '%TEST%' AND
                R.ROUTE_ID NOT LIKE '%HOT%' AND
                R.ROUTE_ID NOT LIKE '%HS%' AND
                R.ROUTE_ID NOT LIKE '%CL%' ) 
	AND    (
                UPPER(R.DESCRIPTION ) NOT LIKE '%BASE%' AND
                UPPER(R.DESCRIPTION ) NOT LIKE '%COUR%' AND
                UPPER(R.DESCRIPTION ) NOT LIKE '%CLINIC%' AND
                UPPER(R.DESCRIPTION )NOT LIKE '%HAL%'AND
                UPPER(R.DESCRIPTION) NOT LIKE '%TEST%' AND
                UPPER(R.DESCRIPTION) NOT LIKE '%HOT%' AND
                UPPER(R.DESCRIPTION) NOT LIKE '%HS%' ) 
      
      [CONDITION]