SELECT
RTRIM(E.B5JPDC) AS Acis_Id,
LOWER(RTRIM(E.B5GUT5)) AS Address,
E.B5PZCT as Email_Type_Code,
E.B5WQDT as Effective_Date,
E.B5WRDT as End_Date,
RTRIM(ET.B4GTT5) AS Email_Type
FROM DTAPDBRC.BPTEMLP E
LEFT JOIN DTAPDBRC.BPTETLP ET ON (E.B5PZCT = ET.B4PZCT)
WHERE E.B5AGTS = 'A' AND E.B5WQDT <= ? AND (E.B5WRDT = 0 OR E.B5WRDT >= ?)
[CONDITION]
ORDER BY E.B5PZCT
FETCH FIRST 500 ROWS ONLY WITH UR