//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package com.apria.web.services.ecm.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

@XmlRootElement(name = "getEcmDocumentResponse", namespace = "http://ecm.services.web.apria.com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getEcmDocumentResponse", namespace = "http://ecm.services.web.apria.com/")
public class GetEcmDocumentResponse {

    @XmlElement(name = "return", namespace = "")
    private com.apria.web.services.ecm.vo.DocResponse _return;

    /**
     * 
     * @return
     *     returns DocResponse
     */
    public com.apria.web.services.ecm.vo.DocResponse getReturn() {
        return this._return;
    }

    /**
     * 
     * @param _return
     *     the value for the _return property
     */
    public void setReturn(com.apria.web.services.ecm.vo.DocResponse _return) {
        this._return = _return;
    }

}
