<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="AES_AgentDetails_IntfExport1_AES_AgentDetails_IntfHttp_Service" targetNamespace="http://AES_GetAgentDetails_Lib_1_0/com/apria/services/aes/agentdetails/AES_AgentDetails_Intf/Binding" xmlns:Port_0="http://AES_GetAgentDetails_Lib_1_0/com/apria/services/aes/agentdetails/AES_AgentDetails_Intf" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:this="http://AES_GetAgentDetails_Lib_1_0/com/apria/services/aes/agentdetails/AES_AgentDetails_Intf/Binding" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <wsdl:import location="AES_AgentDetails_Intf.wsdl" namespace="http://AES_GetAgentDetails_Lib_1_0/com/apria/services/aes/agentdetails/AES_AgentDetails_Intf">
    </wsdl:import>
  <wsdl:binding name="AES_AgentDetails_IntfExport1_AES_AgentDetails_IntfHttpBinding" type="Port_0:AES_AgentDetails_Intf">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="getAgentDetailsById">
      <soap:operation soapAction=""/>
      <wsdl:input name="getAgentDetailsByIdRequest">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="getAgentDetailsByIdResponse">
        <soap:body use="literal"/>
      </wsdl:output>
      <wsdl:fault name="fault">
        <soap:fault name="fault" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="AES_AgentDetails_Intf_1_0">
    <wsdl:port binding="this:AES_AgentDetails_IntfExport1_AES_AgentDetails_IntfHttpBinding" name="AES_AgentDetails_Intf_1_0_AES_AgentDetails_IntfHttpPort">
      <soap:address location="http://aesb.apria.com:80/AES_GetAgentDetails_Svcs_1_0Web/sca/AES_AgentDetails_Intf_1_0"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>