SELECT 
RTRIM(A.C7JPDC) AS Agent_Id,
RTRIM(A.C7HJXT) AS First_Name,
RTRIM(A.C7HLXT) AS Last_Name
FROM DTAPDBRC.BCSTAGP A
WHERE A.C7AGTS = 'A'
[CONDITION]
ORDER BY A.C7JPDC
FETCH FIRST 200 ROWS ONLY WITH UR