SELECT
RTRIM(A.BTILCU) AS Agent_Id,
RTRIM(A.BTXVCR) AS Code,
A.BTL1DZ AS Effective_Date,
A.BTL2DZ AS End_Date,
RTRIM(B.BRRWT2) AS Description
FROM DTAPDBRC.BCSTAHP A
LEFT JOIN DTAPDBRC.BATRHDP B ON A.BTXWCR = B.BRXQCR AND A.BTXVCR = B.BRXPCR
WHERE (A.BTL2DZ = '0001-01-01' OR A.BTL2DZ >= CURRENT_DATE) AND A.BTAGTS = 'A'
[CONDITION]
ORDER BY A.BTILCU, A.BTL1DZ DESC
FETCH FIRST 200 ROWS ONLY WITH UR