SELECT 
RTRIM(A.A8JPDC) AS Agent_Id,
A.A8V7DZ AS Effective_Date,
A.A8V8DZ AS End_Date,
RTRIM(A.A8BCT5) AS Contact_Name,
RTRIM(A.A8BDT5) AS Title,
RTRIM(A.A8BJT5) AS Email,
RTRIM(B.BCNMCT) AS Contact_Reason,
RTRIM(A.A8BYT5) AS Notes,
RTRIM(A.A8BET5) AS Department,
RTRIM(A.A8BFT5) AS Phone,
RTRIM(A.A8BGT5) AS Phone_Ext,
RTRIM(A.A8BHT5) AS Fax,
RTRIM(A.A8QFAX) AS Prefered_Contact_Method
FROM DTAPDBRC.BAPCIRP A 
INNER JOIN DTAPDBRC.BAPCXRP B 
	ON A.A8JPDC = B.BCJPDC AND A.A8S7N1 = B.BCTBN1
WHERE  (A.A8V8DZ = '0001-01-01' OR A.A8V8DZ >= CURRENT_DATE) AND A.A8AGTS = 'A'
[CONDITION]
ORDER BY A.A8JPDC, A.A8V7DZ DESC
FETCH FIRST 200 ROWS ONLY WITH UR

