SELECT
RTRIM(A.A9JPDC) AS Agent_Id,
A.A9WBDZ AS Effective_Date,
A.A9WKDZ AS End_Date,
RTRIM(A.A9NTCT) AS Product_Category,
RTRIM(A.A9NRCT) AS Ops_Class,
RTRIM(A.A9B2VB) AS Commitment,
RTRIM(A.A9TIN1) AS Number_Days,
RTRIM(A9BWT5) AS Notes
FROM DTAPDBRC.BAPDCRP A
WHERE (A.A9WKDZ = '0001-01-01' OR A.A9WKDZ >= CURRENT_DATE) AND A.A9AGTS = 'A'
[CONDITION]
ORDER BY A.A9JPDC, A.A9WBDZ DESC
FETCH FIRST 200 ROWS ONLY WITH UR